language: cpp

compiler:  
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-4.9
        env:
           - MATRIX_EVAL="CXX=g++-4.9"

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script: make 
