language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

install:
# Install a newer version of CMake for our Linux environment. 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate http://cmake.org/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.7.1-Linux-x86_64.tar.gz
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.7.1-Linux-x86_64/bin:$PATH                                                    ;fi

before_script:
  - git clone https://github.com/rendering-io/LLVM.git LLVM
  - ln -s . LLVM/projects/ShaderC
  - mkdir build
  - cd build
  - cmake ../LLVM

script: make 
